#FROM geerlingguy/php-apache:latest

#RUN rm /var/www/html/index.html
#COPY index.php /var/www/html/index.php

#COPY ./ports.conf /etc/apache2/port.conf
#COPY ./apache.conf /etc/apache2/sites-enabled/000-default.conf

FROM python:3.9.7

COPY ./src /app/src
COPY ./requirements.txt /app

WORKDIR /app

RUN pip install -r requirements.txt

EXPOSE 8000

CMD ["uvicorn", "src.main:app", "--host=0.0.0.0", "--reload"]